pipeline{
    agent any
    environment {
        projetoTeste = "$WORKSPACE/Jenkins"
    }

    stages{
        stage('wrapper'){
            steps{
                echo''
                dir("$projetoTeste"){
                    sh'gradle wrapper'
                }
            }
        }
        stage('Test') {
            steps{
                echo'kkkkkk'
                dir("$projetoTeste"){
                    sh'./gradlew test'
                }
            }
        }
        stage('build apk'){
            steps{
                echo'kkkk'
                dir("$projetoTeste") {
                    sh'./gradlew assembleRelease'
                }
            }
        }
        stage('Arquivando APK'){
            steps{
                echo'arquivando apk gerado'
                arquiveArtifacts artifacts: '**/app-release-unsigned.apk', fingerprint: true, allowEmptyArquive: true
                echo'Salvando tag'
            }
        }
    }
}